import { Scan } from '../types/scan';
import { Finding } from '../types/finding';
import { AgentTimelineEvent } from '../types/agent';

export const SYNTHETIC_TOKEN = 'SYNTHETIC_TOKEN';

export const INITIAL_FINDINGS: Finding[] = [
  {
    id: 'fnd-sqli-01',
    scanId: 'scan-8f2a1b9c',
    title: 'SQL Injection in Customer Search Endpoint',
    severity: 'critical',
    target: 'staging.payments.internal',
    asset: 'https://staging.payments.internal/api/v1/customers/search',
    description: 'The search parameter is concatenated directly into a PostgreSQL SQL query without parameterized binding, allowing blind SQL injection and arbitrary database query execution.',
    tool: 'nuclei_web_scan',
    confidence: 'high',
    status: 'open',
    detectedAt: '2026-09-23T14:15:32Z',
    evidence: {
      request: 'GET /api/v1/customers/search?q=test%27+OR+1%3D1--+HTTP/1.1\nHost: staging.payments.internal\nUser-Agent: CyberSec AI/1.0-Synthetic',
      response: 'HTTP/1.1 200 OK\nContent-Type: application/json\nX-Database-Latency: 184ms\n\n[{"id": 1, "name": "Admin Root", "email": "admin@internal.corp", "role": "superuser"}]',
      matchedPattern: "syntax error at or near 'OR 1=1'",
      extractedData: {
        parameter: 'q',
        database: 'PostgreSQL 15.2',
        injectionType: 'Boolean-based Blind / Error-based',
      },
    },
    aiAnalysis: {
      summary: 'High-confidence SQL injection vulnerability identified in the query parameter. Unauthenticated remote threat actors can bypass authentication, dump database records, or modify payment ledger tables.',
      impact: 'Full read/write compromise of customer transactional records, PII leakage, and administrative privilege escalation.',
      attackVector: 'Unauthenticated Remote / HTTP GET Parameter',
      exploitLikelihood: 'High',
    },
    remediation: {
      summary: 'Replace raw string formatting with parameterized prepared queries or an Object-Relational Mapper (ORM).',
      steps: [
        'Enforce parameterized prepared queries across all database access layers.',
        'Apply strict input sanitization restricting search queries to alphanumeric characters.',
        'Ensure the database service user operates under least-privilege permissions without superuser access.',
      ],
      codeSnippet: {
        language: 'python',
        before: 'cursor.execute(f"SELECT * FROM customers WHERE name LIKE \'%{query}%\'")',
        after: 'cursor.execute("SELECT * FROM customers WHERE name ILIKE %s", (f"%{query}%",))',
        description: 'Use parameterized placeholders (%s) rather than Python string formatting (f-strings).',
      },
    },
    references: [
      'https://owasp.org/www-community/attacks/SQL_Injection',
      'https://cwe.mitre.org/data/definitions/89.html',
    ],
    isSynthetic: true,
  },
  {
    id: 'fnd-actuator-02',
    scanId: 'scan-8f2a1b9c',
    title: 'Unauthenticated Spring Boot Actuator /env Endpoint',
    severity: 'high',
    target: 'staging.payments.internal',
    asset: 'https://staging.payments.internal/actuator/env',
    description: 'Production Spring Boot Actuator endpoints are exposed publicly without authentication, disclosing internal environment variables, database hosts, and partial API keys.',
    tool: 'httpx_probe',
    confidence: 'high',
    status: 'open',
    detectedAt: '2026-09-23T14:14:10Z',
    evidence: {
      request: 'GET /actuator/env HTTP/1.1\nHost: staging.payments.internal\nAccept: application/json',
      response: 'HTTP/1.1 200 OK\nContent-Type: application/vnd.spring-boot.actuator.v3+json\n\n{"activeProfiles":["staging"],"propertySources":[{"name":"systemEnvironment","properties":{"DB_HOST":{"value":"db-cluster.internal.corp"}}}]}',
      matchedPattern: '"activeProfiles":["staging"]',
      extractedData: {
        disclosedEndpoints: ['/actuator/env', '/actuator/beans', '/actuator/health'],
        exposedKeyPrefixes: ['DB_HOST', 'REDIS_CLUSTER_URL'],
      },
    },
    aiAnalysis: {
      summary: 'Exposed actuator routes provide internal reconnaissance data. Attackers can map network architecture and leverage connection strings for lateral movement.',
      impact: 'Information disclosure enabling lateral movement and internal credential targeted attacks.',
      attackVector: 'Unauthenticated Remote HTTP GET',
      exploitLikelihood: 'High',
    },
    remediation: {
      summary: 'Restrict Spring Boot actuator web exposure in application.yml and enforce Spring Security filters.',
      steps: [
        'Modify application.yml to only expose the health endpoint: management.endpoints.web.exposure.include: health',
        'Place administrative endpoints behind reverse proxy access control or corporate VPN subnets.',
      ],
      codeSnippet: {
        language: 'yaml',
        before: 'management:\n  endpoints:\n    web:\n      exposure:\n        include: "*"',
        after: 'management:\n  endpoints:\n    web:\n      exposure:\n        include: "health,info"\n  endpoint:\n    health:\n      show-details: when_authorized',
        description: 'Disable wildcard endpoint exposure in application configuration.',
      },
    },
    references: [
      'https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.security',
      'https://cwe.mitre.org/data/definitions/200.html',
    ],
    isSynthetic: true,
  },
  {
    id: 'fnd-tls-03',
    scanId: 'scan-8f2a1b9c',
    title: 'Deprecated TLS 1.0 & 1.1 Cipher Suites Enabled',
    severity: 'medium',
    target: 'staging.payments.internal',
    asset: 'https://staging.payments.internal:443',
    description: 'The server accepts handshakes using deprecated TLS 1.0 and TLS 1.1 protocols containing CBC-mode ciphers vulnerable to POODLE and BEAST attacks.',
    tool: 'mock_port_scan',
    confidence: 'high',
    status: 'open',
    detectedAt: '2026-09-23T14:12:05Z',
    evidence: {
      rawSnippet: 'TLS Handshake Success: Protocol TLSv1.0, Cipher: TLS_RSA_WITH_AES_128_CBC_SHA\nTLS Handshake Success: Protocol TLSv1.1, Cipher: TLS_RSA_WITH_AES_256_CBC_SHA',
      extractedData: {
        supportedProtocols: ['TLSv1.0', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3'],
        insecureCiphers: ['TLS_RSA_WITH_AES_128_CBC_SHA'],
      },
    },
    aiAnalysis: {
      summary: 'Deprecated cryptographic protocols fail compliance standards (PCI-DSS 3.2.1, NIST SP 800-52r2) and allow man-in-the-middle decryption.',
      impact: 'Eavesdropping on encrypted transmission between clients and payment endpoints.',
      attackVector: 'Network MitM / Passive Interception',
      exploitLikelihood: 'Medium',
    },
    remediation: {
      summary: 'Enforce minimum TLS 1.2 or TLS 1.3 protocol versions on reverse proxy/load balancer configs.',
      steps: [
        'Disable TLS 1.0 and 1.1 in Nginx/HAProxy TLS configuration.',
        'Configure forward secrecy ciphers (ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-GCM-SHA256).',
      ],
      codeSnippet: {
        language: 'nginx',
        before: 'ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;',
        after: 'ssl_protocols TLSv1.2 TLSv1.3;\nssl_ciphers HIGH:!aNULL:!MD5:!3DES;',
        description: 'Disable legacy protocol handshakes in nginx.conf',
      },
    },
    references: [
      'https://cwe.mitre.org/data/definitions/326.html',
      'https://wiki.mozilla.org/Security/Server_Side_TLS',
    ],
    isSynthetic: true,
  },
  {
    id: 'fnd-headers-04',
    scanId: 'scan-8f2a1b9c',
    title: 'Missing Content-Security-Policy & Strict-Transport-Security',
    severity: 'info',
    target: 'staging.payments.internal',
    asset: 'https://staging.payments.internal/',
    description: 'HTTP response headers lack Strict-Transport-Security (HSTS) and Content-Security-Policy (CSP) headers, allowing potential protocol downgrades and clickjacking.',
    tool: 'httpx_probe',
    confidence: 'high',
    status: 'resolved',
    detectedAt: '2026-09-23T14:12:30Z',
    evidence: {
      request: 'HEAD / HTTP/1.1\nHost: staging.payments.internal',
      response: 'HTTP/1.1 200 OK\nServer: nginx/1.24.0\nContent-Type: text/html; charset=UTF-8\nConnection: keep-alive',
      extractedData: {
        missingHeaders: ['Content-Security-Policy', 'Strict-Transport-Security', 'X-Frame-Options'],
      },
    },
    aiAnalysis: {
      summary: 'Security headers provide defense-in-depth against client-side script injection and ensure communication stays strictly over HTTPS.',
      impact: 'Minor exposure to MIME-type sniffing, cross-site framing, and plain HTTP fallback.',
      attackVector: 'Browser / Client-Side Script Injection',
      exploitLikelihood: 'Low',
    },
    remediation: {
      summary: 'Inject baseline security headers at edge proxy or API gateway.',
      steps: [
        'Add Strict-Transport-Security with at least 1-year max-age and includeSubDomains.',
        'Implement Content-Security-Policy and X-Content-Type-Options: nosniff.',
      ],
      codeSnippet: {
        language: 'nginx',
        after: 'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;\nadd_header X-Content-Type-Options "nosniff" always;\nadd_header X-Frame-Options "DENY" always;',
        description: 'Standard security header directives in web server configuration.',
      },
    },
    references: ['https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP'],
    isSynthetic: true,
  },
  {
    id: 'fnd-idor-05',
    scanId: 'scan-4e9d72c1',
    title: 'Insecure Direct Object Reference (IDOR) on Invoice PDF',
    severity: 'high',
    target: 'api.auth-portal.test',
    asset: 'https://api.auth-portal.test/api/v2/invoices/INV-90421',
    description: 'Arbitrary invoice records can be fetched by iterating invoice IDs without validating ownership against the currently authenticated session.',
    tool: 'nuclei_web_scan',
    confidence: 'high',
    status: 'open',
    detectedAt: '2026-09-23T11:24:08Z',
    evidence: {
      request: `GET /api/v2/invoices/INV-90422 HTTP/1.1\nHost: api.auth-portal.test\nAuthorization: Bearer ${SYNTHETIC_TOKEN}`,
      response: 'HTTP/1.1 200 OK\nContent-Type: application/json\n\n{"invoiceId": "INV-90422", "ownerId": "usr_other_tenant", "amount": "$14,500.00"}',
      matchedPattern: '"ownerId": "usr_other_tenant"',
    },
    aiAnalysis: {
      summary: 'Horizontal privilege escalation allowing one tenant to access financial billing documents belonging to other organizations.',
      impact: 'Confidentiality breach of sensitive vendor pricing and tenant invoice data.',
      attackVector: 'Authenticated Remote / Predictable ID Enumeration',
      exploitLikelihood: 'High',
    },
    remediation: {
      summary: 'Enforce object-level access control verifying caller authorization before returning resource representations.',
      steps: [
        'In controller layer, assert that invoice.tenant_id matches request.user.tenant_id.',
        'Use non-sequential GUIDs or UUIDv4 identifiers for public-facing resource references.',
      ],
      codeSnippet: {
        language: 'typescript',
        before: 'const invoice = await Invoice.findById(req.params.id);',
        after: 'const invoice = await Invoice.findOne({ id: req.params.id, orgId: req.user.orgId });\nif (!invoice) throw new ForbiddenException("Access denied");',
        description: 'Verify current user organization scope in database query.',
      },
    },
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html'],
    isSynthetic: true,
  },
  {
    id: 'fnd-cors-06',
    scanId: 'scan-4e9d72c1',
    title: 'Overly Permissive CORS Access-Control-Allow-Origin: *',
    severity: 'medium',
    target: 'api.auth-portal.test',
    asset: 'https://api.auth-portal.test/api/v2/userinfo',
    description: 'The API reflects the Origin header with Access-Control-Allow-Credentials: true and Access-Control-Allow-Origin: * or dynamically echoes untrusted origins.',
    tool: 'httpx_probe',
    confidence: 'high',
    status: 'open',
    detectedAt: '2026-09-23T11:21:40Z',
    evidence: {
      request: 'OPTIONS /api/v2/userinfo HTTP/1.1\nHost: api.auth-portal.test\nOrigin: https://evil-attacker.example\nAccess-Control-Request-Method: GET',
      response: 'HTTP/1.1 204 No Content\nAccess-Control-Allow-Origin: https://evil-attacker.example\nAccess-Control-Allow-Credentials: true',
    },
    aiAnalysis: {
      summary: 'Misconfigured CORS policy allows arbitrary websites to read authenticated responses if a victim visits an attacker-controlled webpage.',
      impact: 'Session hijacking or unauthorized data theft across origins.',
      attackVector: 'Cross-Site / Client Browser Request',
      exploitLikelihood: 'Medium',
    },
    remediation: {
      summary: 'Restrict allowed CORS origins to explicit, whitelisted first-party domain names.',
      steps: [
        'Define a strict domain whitelist array in middleware configuration.',
        'Never dynamically reflect origin header if credentials flag is enabled.',
      ],
    },
    references: ['https://portswigger.net/web-security/cors'],
    isSynthetic: true,
  },
  {
    id: 'fnd-port-07',
    scanId: 'scan-1a8f9024',
    title: 'Cleartext HTTP Service on Port 8080 (No TLS)',
    severity: 'low',
    target: 'demo.local',
    asset: 'http://demo.local:8080',
    description: 'An administrative development web portal is accessible over cleartext HTTP without encryption or mandatory redirect to HTTPS.',
    tool: 'mock_port_scan',
    confidence: 'high',
    status: 'open',
    detectedAt: '2026-09-22T10:00:05Z',
    evidence: {
      rawSnippet: 'Scanned 3 ports on demo.local: 3 open (80, 443, 8080). Service on 8080: Apache Tomcat/9.0.41 (Dev)',
    },
    aiAnalysis: {
      summary: 'Cleartext communications can be intercepted on local LAN or unencrypted wireless networks.',
      impact: 'Credential sniffing if administrators authenticate over unencrypted HTTP.',
      attackVector: 'Local Network Eavesdropping',
      exploitLikelihood: 'Low',
    },
    remediation: {
      summary: 'Configure automatic HTTP-to-HTTPS redirect on port 8080 or bind administrative port to localhost interface.',
      steps: [
        'Bind internal dev service to 127.0.0.1:8080 instead of 0.0.0.0.',
        'Require TLS termination via reverse proxy.',
      ],
    },
    references: ['https://cwe.mitre.org/data/definitions/319.html'],
    isSynthetic: true,
  },
  {
    id: 'fnd-git-08',
    scanId: 'scan-1a8f9024',
    title: 'Exposed .git Repository Directory',
    severity: 'low',
    target: 'demo.local',
    asset: 'http://demo.local/.git/config',
    description: 'Source code management directory .git/HEAD and .git/config are accessible, exposing internal branch names and repository commit hashes.',
    tool: 'nuclei_web_scan',
    confidence: 'high',
    status: 'resolved',
    detectedAt: '2026-09-22T10:01:12Z',
    evidence: {
      request: 'GET /.git/config HTTP/1.1\nHost: demo.local',
      response: 'HTTP/1.1 200 OK\n\n[core]\n\trepositoryformatversion = 0\n\tfilemode = true\n\tbare = false\n\tlogallrefupdates = true',
    },
    aiAnalysis: {
      summary: 'Public .git folders allow threat actors to recreate the entire codebase history and inspect past hardcoded credentials.',
      impact: 'Source code disclosure and exposure of historical secrets.',
      attackVector: 'Unauthenticated HTTP GET',
      exploitLikelihood: 'Medium',
    },
    remediation: {
      summary: 'Block access to hidden files and dotfiles (.git, .env) in web server configuration.',
      steps: [
        'Add a deny rule for all files matching /\\..* in web server configurations.',
      ],
      codeSnippet: {
        language: 'nginx',
        after: 'location ~ /\\.(?!well-known) {\n    deny all;\n    return 404;\n}',
        description: 'Block dotfiles in nginx configuration',
      },
    },
    references: ['https://cwe.mitre.org/data/definitions/538.html'],
    isSynthetic: true,
  },
];

export const INITIAL_SCANS: Scan[] = [
  {
    id: 'scan-8f2a1b9c',
    target: 'staging.payments.internal',
    profile: 'full_assessment',
    status: 'finished',
    startedAt: '2026-09-23T14:10:00Z',
    completedAt: '2026-09-23T14:16:15Z',
    findingsCount: {
      critical: 1,
      high: 1,
      medium: 1,
      low: 0,
      info: 1,
      total: 4,
    },
    currentStep: 6,
    totalSteps: 6,
    goal: 'Comprehensive assessment of staging payment gateway, API authorization, and service mesh.',
    notes: 'Autonomous multi-phase audit completed with 4 findings recorded.',
    isSimulated: true,
  },
  {
    id: 'scan-4e9d72c1',
    target: 'api.auth-portal.test',
    profile: 'web_assessment',
    status: 'finished',
    startedAt: '2026-09-23T11:20:00Z',
    completedAt: '2026-09-23T11:25:30Z',
    findingsCount: {
      critical: 0,
      high: 1,
      medium: 1,
      low: 0,
      info: 0,
      total: 2,
    },
    currentStep: 5,
    totalSteps: 5,
    goal: 'Web application vulnerability assessment for authentication service endpoints.',
    notes: 'OWASP Top 10 surface checks executed successfully.',
    isSimulated: true,
  },
  {
    id: 'scan-1a8f9024',
    target: 'demo.local',
    profile: 'recon',
    status: 'finished',
    startedAt: '2026-09-22T10:00:00Z',
    completedAt: '2026-09-22T10:02:10Z',
    findingsCount: {
      critical: 0,
      high: 0,
      medium: 0,
      low: 1,
      info: 1,
      total: 2,
    },
    currentStep: 4,
    totalSteps: 4,
    goal: 'Perform initial passive & active reconnaissance and port discovery.',
    notes: 'Port discovery revealed open services on 80, 443, 8080.',
    isSimulated: true,
  },
];

export const TIMELINE_TEMPLATES: Record<string, Omit<AgentTimelineEvent, 'id' | 'timestamp'>[]> = {
  recon: [
    {
      step: 1,
      type: 'run.started',
      title: 'Target Scope Validated',
      description: 'Resolved target host, verified network route reachability, and checked user authorization parameters.',
      tool: 'scope_verifier',
      status: 'completed',
      durationMs: 820,
      reasoning: 'Autonomous execution requires confirming host boundaries to prevent out-of-scope testing.',
    },
    {
      step: 2,
      type: 'tool.finished',
      title: 'Nmap Port & Service Discovery Completed',
      description: 'Probed top 1000 standard network ports. Detected open ports: 80 (HTTP), 443 (HTTPS), 8080 (Dev Proxy).',
      tool: 'mock_port_scan',
      status: 'completed',
      durationMs: 2400,
      reasoning: 'Identifying exposed listening services establishes attack surface boundaries.',
    },
    {
      step: 3,
      type: 'decision.proposed',
      title: 'AI Planner Analyzed Port Fingerprints',
      description: 'Synthesizing port banners: identified potential unencrypted HTTP service on port 8080.',
      tool: 'ai_reasoner',
      status: 'completed',
      durationMs: 1100,
      reasoning: 'Cleartext web servers on non-standard ports warrant immediate vulnerability classification.',
    },
    {
      step: 4,
      type: 'run.finished',
      title: 'Reconnaissance Assessment Finalized',
      description: 'Generated preliminary attack surface topology. Findings normalized and recorded to database.',
      tool: 'reporter',
      status: 'completed',
      durationMs: 650,
      reasoning: 'Run concluded. 2 findings identified.',
    },
  ],
  web_assessment: [
    {
      step: 1,
      type: 'run.started',
      title: 'Target Scope Validated',
      description: 'Target URL verified, SSL handshake checked, baseline response headers mapped.',
      tool: 'scope_verifier',
      status: 'completed',
      durationMs: 950,
      reasoning: 'Establishing HTTP baseline headers and connection stability before fuzzing.',
    },
    {
      step: 2,
      type: 'tool.finished',
      title: 'HTTP Probing & Endpoint Discovery (httpx)',
      description: 'Identified 18 endpoints across /api/v1 and /api/v2. Discovered exposed CORS headers and debug paths.',
      tool: 'httpx_probe',
      status: 'completed',
      durationMs: 3100,
      reasoning: 'Crawling routes discovers hidden API documentation and unlinked entrypoints.',
    },
    {
      step: 3,
      type: 'decision.proposed',
      title: 'AI Reasoning: Targeted OWASP Vectors',
      description: 'Planner selected Nuclei security templates: IDOR parameter tampering and CORS reflection checks.',
      tool: 'ai_reasoner',
      status: 'completed',
      durationMs: 1400,
      reasoning: 'Observed predictable numeric IDs in invoice endpoints; selecting IDOR test suite.',
    },
    {
      step: 4,
      type: 'finding.recorded',
      title: 'Nuclei Scan: Security Findings Identified',
      description: 'Confirmed Insecure Direct Object Reference (IDOR) and permissive CORS wildcards on userinfo route.',
      tool: 'nuclei_web_scan',
      status: 'completed',
      durationMs: 4200,
      reasoning: 'Vulnerability patterns confirmed with positive server feedback evidence.',
    },
    {
      step: 5,
      type: 'run.finished',
      title: 'Web Assessment Run Completed',
      description: 'Compiled vulnerability ledger, generated remediation advice, and normalized CVE correlations.',
      tool: 'reporter',
      status: 'completed',
      durationMs: 800,
      reasoning: 'Terminal state reached successfully.',
    },
  ],
  full_assessment: [
    {
      step: 1,
      type: 'run.started',
      title: 'Target Scope & Authorization Verified',
      description: 'Host resolution validated. Safe scan boundaries initialized with mock security controls.',
      tool: 'scope_verifier',
      status: 'completed',
      durationMs: 1100,
      reasoning: 'Validating legal authorization parameters before multi-phase testing begins.',
    },
    {
      step: 2,
      type: 'tool.finished',
      title: 'Port Scan & Protocol Analysis (Nmap)',
      description: 'Detected ports 80, 443, 8080. Analyzed SSL cipher suites: discovered weak TLS 1.0/1.1 protocols.',
      tool: 'mock_port_scan',
      status: 'completed',
      durationMs: 2900,
      reasoning: 'Network protocol inspection exposes legacy cryptographic vulnerabilities.',
    },
    {
      step: 3,
      type: 'tool.finished',
      title: 'Web Surface & Service Probing (httpx)',
      description: 'Identified 26 active endpoints. Discovered unprotected Spring Boot Actuator /env endpoint.',
      tool: 'httpx_probe',
      status: 'completed',
      durationMs: 3400,
      reasoning: 'Probing actuator paths discovers sensitive system configuration leakage.',
    },
    {
      step: 4,
      type: 'decision.proposed',
      title: 'AI Planner Evaluated Injection Vectors',
      description: 'AI detected raw database query reflection in /api/v1/customers/search. Selected SQLi fuzzing payload.',
      tool: 'ai_reasoner',
      status: 'completed',
      durationMs: 1800,
      reasoning: 'Heuristic analysis indicated unescaped quotes in search parameters; launching payload verification.',
    },
    {
      step: 5,
      type: 'finding.recorded',
      title: 'Critical Vulnerability Confirmed (Nuclei)',
      description: 'SQL Injection confirmed in customer search endpoint. Synthetic database error extracted.',
      tool: 'nuclei_full',
      status: 'completed',
      durationMs: 4600,
      reasoning: 'High-severity finding recorded. Immediate remediation guidance prioritized.',
    },
    {
      step: 6,
      type: 'run.finished',
      title: 'Full Assessment Synthesized & Completed',
      description: 'Autonomous execution finalized. 4 findings recorded across critical, high, medium, and info tiers.',
      tool: 'reporter',
      status: 'completed',
      durationMs: 1200,
      reasoning: 'All phases concluded. Final pentest report ready for review.',
    },
  ],
};
